# Generated by Django 3.1.5 on 2021-02-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210218_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default='417XT0FSI', max_length=200),
        ),
    ]
