# Generated by Django 3.1.5 on 2021-02-22 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customers', '0004_auto_20210219_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default='68ZH6WEAA', max_length=200),
        ),
        migrations.DeleteModel(
            name='UserTokenizer',
        ),
        migrations.AddField(
            model_name='useraccessgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
