# Generated by Django 3.1.5 on 2021-02-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20210223_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default='R78L0F43M', max_length=200),
        ),
    ]
