# Generated by Django 3.1.5 on 2021-03-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20210301_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default='330H3E62A', max_length=200),
        ),
    ]
