# Generated by Django 3.1.5 on 2021-03-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20210302_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default='6723H4BUH', max_length=200),
        ),
    ]
