# Generated by Django 3.1.5 on 2021-03-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20210303_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default='6U711YB7J', max_length=200),
        ),
    ]
