# Generated by Django 3.1.5 on 2021-03-03 07:54

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_auto_20210303_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default=customers.models.getCode, max_length=200),
        ),
    ]
