# Generated by Django 3.1.5 on 2021-02-18 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210218_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('b719de5d-2b0d-4526-89c9-a075d96bab7e')),
        ),
    ]
