# Generated by Django 3.1.5 on 2021-02-22 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210218_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('05a92d21-718d-4d14-a965-97e4f784f64a')),
        ),
    ]
