# Generated by Django 3.1.5 on 2021-02-23 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210222_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('0ad5e8a1-50c4-496b-9272-10ef1562313b')),
        ),
    ]
