# Generated by Django 3.1.5 on 2021-02-23 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210223_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('98c0981b-e2e9-470a-8890-1ba1ac39e1f6')),
        ),
    ]
