# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Lint with flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --exclude .git,__pycache__,build,dist,venv --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test the application
        run: |
          source venv/bin/activate
          ./manage.py test --keepdb -v 2

      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.SAV_HEROKU_TOKEN }}
          HEROKU_APP_NAME: ${{ secrets.SAV_HEROKU_APPNAME }}
        if: github.ref == 'refs/heads/main' && job.status == 'success'
        run: |
          git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
          heroku config:set DISABLE_COLLECTSTATIC=1
          git push heroku HEAD:master -f
